BUZZ_NUM_GUESSES = 10
BUZZ_THRESHOLD = 0.5
TRAIN_TYPE = 'elmo'  # elmo or tfidf
BUZZ_TYPE = 'simple'  # simple or rnn
OPTIONS_FILE = "src/data/options_file.json"
WEIGHTS_FILE = "src/data/weights_file.json"
OPTIONS_FILE2 = "../src/data/options_file.json"
WEIGHTS_FILE2 = "../src/data/weights_file.json"
ELMO_MODEL_PATH = 'src/qanta/elmo.pickle'
TFIDF_MODEL_PATH ='tfidf.pickle'
BUZZER_PATH = 'buzzer.pickle'
